Run eval.py to test the repaired network:
    *python eval.py*